// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShSKOOp2m0jJbBwBDZ-Wo5f-Xju4zBiY',
    appId: '1:224437694991:web:d4595ddff006665538297a',
    messagingSenderId: '224437694991',
    projectId: 'project-gweh-8d478',
    authDomain: 'project-gweh-8d478.firebaseapp.com',
    storageBucket: 'project-gweh-8d478.firebasestorage.app',
    measurementId: 'G-TYGBNR9BEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnX2XFxzDCIg3npnaDecZ5NzsZeCwZC_A',
    appId: '1:224437694991:android:32f29c57bbecedb238297a',
    messagingSenderId: '224437694991',
    projectId: 'project-gweh-8d478',
    storageBucket: 'project-gweh-8d478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlDIFTFZh9nP9HdhZzapeK2BA-HqY0Tc',
    appId: '1:224437694991:ios:0988062155d3538338297a',
    messagingSenderId: '224437694991',
    projectId: 'project-gweh-8d478',
    storageBucket: 'project-gweh-8d478.firebasestorage.app',
    iosBundleId: 'com.example.ppbFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIlDIFTFZh9nP9HdhZzapeK2BA-HqY0Tc',
    appId: '1:224437694991:ios:0988062155d3538338297a',
    messagingSenderId: '224437694991',
    projectId: 'project-gweh-8d478',
    storageBucket: 'project-gweh-8d478.firebasestorage.app',
    iosBundleId: 'com.example.ppbFp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBShSKOOp2m0jJbBwBDZ-Wo5f-Xju4zBiY',
    appId: '1:224437694991:web:b99aaf60b847dcf538297a',
    messagingSenderId: '224437694991',
    projectId: 'project-gweh-8d478',
    authDomain: 'project-gweh-8d478.firebaseapp.com',
    storageBucket: 'project-gweh-8d478.firebasestorage.app',
    measurementId: 'G-93N18KKV3Y',
  );
}
